### PR TITLE
Fix double comma issue when caching enabled

### LINKED ISSUE #8: OJ encoder emitting extra comma after injecting content in array
See test case at
https://github.com/malomalo/turbostreamer/compare/master...PikachuEXE:fix/caching-content

### PR DESCRIPTION
**Pull request by PikachuEXE**
The issue is due to incorrect implementation:
- We write comma while `Oj::StreamWriter` writes it too in `#map_open` & `#array_open`
- We write comma twice in `#inject`

File change from #5 included for better test coverage

Fixes #8

### CODE REVIEW

**Comment by PikachuEXE** [comment]
dirk
report
rolftimmermans
report

**Comment by PikachuEXE** [comment]
Please let me know if there is anything left to be done to get this PR merged

**Comment by PikachuEXE** [comment]
Hello?

**Comment by PikachuEXE** [comment]
Aloha?

**Comment by PikachuEXE** [comment]
Please give a response?

**Comment by malomalo** [comment]
Hi looking at this now

**Comment by malomalo** [comment]
Look great! Merged!

**Pull request merged**
