### PR TITLE
! Fix Travis build & test against new ruby + rails versions

### PR DESCRIPTION
**Pull request by PikachuEXE**
I fixed Travis build for me own gem after bundler 2 released:

- https://github.com/PikachuEXE/rspec-json_matchers/commit/c8927ff1270c8448b8c69571ebe29981baf1835d
- https://github.com/PikachuEXE/rspec-json_matchers/commit/09489f031b8b75191a963bd8972aff6cac4f2041

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Build is green now
But got to ignore `ruby-head` since can't install old bundler

**Comment by malomalo** [comment]
Test are now passing, dropped Rails 4.2 support and just testing against 5.0+ now. 4.2 works, but jsut not testing against it.

Also added Rails 6.0 support

**Comment by PikachuEXE** [comment]
Yup Rails 4.2 got some bundler version constraint and conflicting bundler 2 on Travis
I just run them but allow them to fail
Still can't find a good fix

**Comment by malomalo** [comment]
I just looked at the Gemfile and the lockfile and it does work.... doesn't mean it should; I've updated the Gemfile to just be v6.0.0.beta3

**Comment by malomalo** [comment]
Do you use Rails 4.2? If you do I can try and getting it running, otherwise think we should just worry about Rails 5+

**Comment by PikachuEXE** [comment]
Nah I just use rails 5.2
4.2 is too old anyway :) (which only receives security updates)

**Pull request merged**
